# name: Deploy Frontend to S3

# on:
#   push:
#     branches:
#       - master
#     paths:
#       - 'apps/frontend/**'
#       - 'packages/**'
#       - 'turbo.json'
#       - 'package.json'
#       - '.github/workflows/deploy-frontend.yml'

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'
#           cache: 'npm'

#       - name: Install Dependencies
#         run: npm ci

#       - name: Debug Secrets
#         run: |
#           echo "AWS_ACCESS_KEY_ID is set"
#           echo "AWS_SECRET_ACCESS_KEY is set"
#           if [ -z "${{ secrets.VITE_API_URL }}" ]; then
#             echo " VITE_API_URL is MISSING!"
#             exit 1
#           else
#             echo " VITE_API_URL is set"
#           fi
#           if [ -z "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" ]; then
#             echo " CLOUDFRONT_DISTRIBUTION_ID is MISSING!"
#           else
#             echo " CLOUDFRONT_DISTRIBUTION_ID is set"
#           fi

#       - name: Set CloudFront Distribution ID as Env
#         run: echo "CLOUDFRONT_DISTRIBUTION_ID=${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" >> $GITHUB_ENV

#       - name: Create .env File
#         run: |
#           echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > apps/frontend/.env

#       - name: Build Frontend
#         run: npm run build --workspace=apps/frontend

#       - name: Deploy to S3
#         uses: jakejarvis/s3-sync-action@master
#         with:
#           args: --delete --cache-control max-age=31536000,public
#         env:
#           AWS_S3_BUCKET: "course-selling-application"
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_REGION: "eu-north-1"
#           SOURCE_DIR: "apps/frontend/dist/"

#       - name: Invalidate CloudFront Cache
#         if: env.CLOUDFRONT_DISTRIBUTION_ID != ''
#         uses: chetan/invalidate-cloudfront-action@v2
#         env:
#           DISTRIBUTION: ${{ env.CLOUDFRONT_DISTRIBUTION_ID }}
#           PATHS: '/*'
#           AWS_REGION: 'eu-north-1'
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
